FROM ubuntu:18.10

RUN apt-get update
RUN apt-get -y install apt-utils aptitude git curl

#RUN apt-get -y install build-essential
#RUN apt-get -y install libpcap-dev libssl-dev

CMD ["/bin/bash"]
#ADD run.sh /tmp/
#CMD ["/bin/bash", "-c", "/tmp/run.sh"]
